services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data:/data/db
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
    ports:
      - 27021:27017
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mongosh --quiet --eval "try { quit(db.adminCommand({ ping: 1 }).ok ? 0 : 1) } catch (e) { quit(1) }"',
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
      target: dev
    ports:
      - "4000:4000"
    env_file:
      - ./apps/backend/.env
    depends_on:
      mongo:
        condition: service_healthy
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      target: dev
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./apps/frontend
          target: /app/apps/frontend

        - action: rebuild
          path: ./apps/frontend/package.json

        - action: rebuild
          path: ./package.json

        - action: rebuild
          path: ./bun.lock
volumes:
  data:
